"""Question: require a signed-in user, drop name/email

Revision ID: 2cba61a87162
Revises: c6eeb3d682b1
Create Date: 2026-09-27 18:40:56.319864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cba61a87162'
down_revision = 'c6eeb3d682b1'
branch_labels = None
depends_on = None


def upgrade():
    # Anonymous questions from before this change have no user to attach to
    # the new required user_id column — clear them rather than fail the
    # migration (the feature only just shipped, so this should be empty).
    op.execute('DELETE FROM questions')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_questions_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_questions_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint('fk_questions_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_questions_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
