"""Add guestbook_entries table

Revision ID: 4b62c255e841
Revises: 937a7da7079c
Create Date: 2026-08-11 19:32:39.884104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b62c255e841'
down_revision = '937a7da7079c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guestbook_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guestbook_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guestbook_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_guestbook_entries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestbook_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guestbook_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_guestbook_entries_created_at'))

    op.drop_table('guestbook_entries')
    # ### end Alembic commands ###
