"""Add login streak fields to User

Revision ID: 6e321d8438b6
Revises: 4b62c255e841
Create Date: 2026-08-30 14:33:58.160861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e321d8438b6'
down_revision = '4b62c255e841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_streak', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('longest_login_streak', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_login_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login_date')
        batch_op.drop_column('longest_login_streak')
        batch_op.drop_column('login_streak')

    # ### end Alembic commands ###
