"""Add gift tracking to redemptions and wish pulls

Revision ID: 7b92cb4a2b8a
Revises: 2cba61a87162
Create Date: 2026-09-27 18:53:21.286688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b92cb4a2b8a'
down_revision = '2cba61a87162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wish_pulls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('reward_type', sa.String(length=20), nullable=False),
    sa.Column('reward_value', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wish_pulls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wish_pulls_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wish_pulls_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('redemptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gifted_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('note', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_redemptions_gifted_by_id'), ['gifted_by_id'], unique=False)
        batch_op.create_foreign_key('fk_redemptions_gifted_by_id_users', 'users', ['gifted_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('redemptions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_redemptions_gifted_by_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_redemptions_gifted_by_id'))
        batch_op.drop_column('note')
        batch_op.drop_column('gifted_by_id')

    with op.batch_alter_table('wish_pulls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wish_pulls_user_id'))
        batch_op.drop_index(batch_op.f('ix_wish_pulls_created_at'))

    op.drop_table('wish_pulls')
    # ### end Alembic commands ###
