"""Add stardust balance and redemptions

Revision ID: 937a7da7079c
Revises: 4589f11e70b7
Create Date: 2026-08-11 17:13:33.608399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937a7da7079c'
down_revision = '4589f11e70b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_slug', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('redemptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_redemptions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stardust_balance', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('stardust_balance')

    with op.batch_alter_table('redemptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_redemptions_user_id'))

    op.drop_table('redemptions')
    # ### end Alembic commands ###
